#!/bin/bash
clear
echo "################## MESSEGE ENCRYPTION TOOL ########################"
echo "Choose any one of the option: "
echo -e "1. Message Encryption" 
echo -e "2. Message Decryption \n"

read n

case $n in
    "1")
        python3 encrypt-msg.py
        ;;
    "2")
        python3 decrypt-msg.py
        ;;
    *)
        echo "Invalid input"
        ;;
esac
