#!/bin/bash

if which python3 && which pip
then
    
    clear

else
    echo "python3 or pip not found..Installing...."
    sudo apt install python3 -y && sudo apt install pip -y && pip3 install -r requirements.txt
    echo "clearing terminal"
    sleep 2
    clear
fi

if which figlet
then
    clear
   
else
    echo "installing packages..."
    sleep 2
    sudo apt install figlet && sudo apt install toilet-y
    sleep 1
fi

figlet -t -k CyberSecurity Tools
echo -e  '\n'
echo "Which tool to use?"
echo "1) Image Encryption"
echo "2) Text Encryption"
 
read ans

case $ans in
    "1")
        python3 main.py
        ;;
    "2")
        bash binder
        ;;
    *)
        echo "Invalid Input"
        ;;
esac
